[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
prost = "0.12"
tokio = { version = "1.36.0", features = ["full"] }
tokio-stream = "0.1.15"
tonic = "0.11"

[build-dependencies]
tonic-build = "0.11"
