[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
prost = "0.14"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
tonic = "0.14"
tonic-prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"
